In [2]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv(r"/Users/owenngimli/Desktop/BPD/data.csv")
df

,CrimeDate,CrimeTime,CrimeCode,Location,Description,Inside/Outside,Weapon,Post,District,Neighborhood,Location 1,Total Incidents
0,11/12/2016,02:35:00,3B,300 SAINT PAUL PL,ROBBERY - STREET,O,NaN,111.0,CENTRAL,Downtown,"(39.2924100000, -76.6140800000)",1
1,11/12/2016,02:56:00,3CF,800 S BROADWAY,ROBBERY - COMMERCIAL,I,FIREARM,213.0,SOUTHEASTERN,Fells Point,"(39.2824200000, -76.5928800000)",1
2,11/12/2016,03:00:00,6D,1500 PENTWOOD RD,LARCENY FROM AUTO,O,NaN,413.0,NORTHEASTERN,Stonewood-Pentwood-Winston,"(39.3480500000, -76.5883400000)",1
3,11/12/2016,03:00:00,6D,6600 MILTON LN,LARCENY FROM AUTO,O,NaN,424.0,NORTHEASTERN,Westfield,"(39.3626300000, -76.5516100000)",1
4,11/12/2016,03:00:00,6E,300 W BALTIMORE ST,LARCENY,O,NaN,111.0,CENTRAL,Downtown,"(39.2893800000, -76.6197100000)",1
...,...,...,...,...,...,...,...,...,...,...,...,...
285802,01/01/2011,22:15:00,4D,6800 MCCLEAN BD,AGG. ASSAULT,I,HANDS,423.0,NORTHEASTERN,Hamilton Hills,"(39.3704700000, -76.5670500000)",1
285803,01/01/2011,22:30:00,6J,3000 ODONNELL ST,LARCENY,I,NaN,232.0,SOUTHEASTERN,Canton,"(39.2804600000, -76.5727300000)",1
285804,01/01/2011,23:00:00,7A,2500 ARUNAH AV,AUTO THEFT,O,NaN,721.0,WESTERN,Evergreen Lawn,"(39.2954200000, -76.6592800000)",1
285805,01/01/2011,23:25:00,4E,100 N MONROE ST,COMMON ASSAULT,I,HANDS,714.0,WESTERN,Penrose/Fayette Street Outreach,"(39.2899900000, -76.6470700000)",1
285806,01/01/2011,23:38:00,4D,800 N FREMONT AV,AGG. ASSAULT,I,HANDS,123.0,WESTERN,Upton,"(39.2981200000, -76.6339100000)",1

In [4]:
df.fillna('Not Registered', inplace=True)

In [5]:
df['CrimeDate'] = pd.to_datetime(df['CrimeDate'])

In [6]:
dateindex = df.set_index("CrimeDate")

In [7]:
monthly = dateindex.resample('M').count()
monthly.loc[monthly["Total Incidents"] == monthly["Total Incidents"].max()] #Most crime are done in july2015

,CrimeTime,CrimeCode,Location,Description,Inside/Outside,Weapon,Post,District,Neighborhood,Location 1,Total Incidents
CrimeDate,,,,,,,,,,,
2015-07-31,4776,4776,4776,4776,4776,4776,4776,4776,4776,4776,4776

In [8]:
july15 = (df['CrimeDate'] >= '2015-07-01') & (df['CrimeDate'] <= '2015-07-31')
df.loc[july15]

,CrimeDate,CrimeTime,CrimeCode,Location,Description,Inside/Outside,Weapon,Post,District,Neighborhood,Location 1,Total Incidents
62685,2015-07-31,21:30:00,6D,1300 KENHILL AVE,LARCENY FROM AUTO,O,Not Registered,332,EASTERN,Berea,"(39.3061800000, -76.5775800000)",1
62686,2015-07-31,21:30:00,6D,1300 LIMIT AVE,LARCENY FROM AUTO,O,Not Registered,414,NORTHEASTERN,Idlewood,"(39.3719000000, -76.5896300000)",1
62687,2015-07-31,2148,1F,4500 EDMONDSON AV,HOMICIDE,Outside,FIREARM,822,SOUTHWESTERN,Rognel Heights,"(39.2934600000, -76.6936500000)",1
62688,2015-07-31,22:00:00,6E,3200 REISTERSTOWN RD,LARCENY,O,Not Registered,611,NORTHWESTERN,Liberty Square,"(39.3236300000, -76.6564400000)",1
62689,2015-07-31,22:00:00,6J,3500 KENTUCKY AVE,LARCENY,O,Not Registered,432,NORTHEASTERN,Belair-Edison,"(39.3189400000, -76.5663900000)",1
...,...,...,...,...,...,...,...,...,...,...,...,...
67456,2015-07-01,23:00:00,4E,900 WICKLOW RD,COMMON ASSAULT,I,HANDS,822,SOUTHWESTERN,Rognel Heights,"(39.2966300000, -76.6888400000)",1
67457,2015-07-01,23:00:00,7A,2200 E MADISON ST,AUTO THEFT,O,Not Registered,321,EASTERN,Middle East,"(39.2997300000, -76.5858900000)",1
67458,2015-07-01,23:15:00,4A,1600 DARLEY AVE,AGG. ASSAULT,O,FIREARM,342,EASTERN,Darley Park,"(39.3147100000, -76.5948400000)",1
67459,2015-07-01,23:57:00,6J,2000 HARFORD RD,LARCENY,O,Not Registered,342,EASTERN,East Baltimore Midway,"(39.3132100000, -76.5989500000)",1
67460,2015-07-01,2315,9S,1600 DARLEY AV,SHOOTING,Outside,FIREARM,342,EASTERN,Darley Park,"(39.3147100000, -76.5950900000)",1

In [9]:
df["Location"].value_counts()

Not Registered                  1623
200 E PRATT ST                   676
300 LIGHT ST                     603
1500 RUSSELL ST                  439
3200 TIOGA PW                    438
                                ...
5300 KENNISON AVE                  1
2900 ROCKWOOD AV                   1
SMALLWOOD ST & WALBROOK AV         1
600 BLOCK FALLSWAY                 1
1300 ANGLESEA ST     #APT T3       1
Name: Location, Length: 25950, dtype: int64

In [10]:
df['District'].value_counts()

NORTHEASTERN      44832
SOUTHEASTERN      39245
CENTRAL           33782
SOUTHERN          33031
NORTHERN          32005
NORTHWESTERN      28690
SOUTHWESTERN      26242
EASTERN           24168
WESTERN           23266
NORTHESTERN         280
SOUTHESTERN         205
Not Registered       58
Central               2
Gay Street            1
Name: District, dtype: int64

In [11]:
df["Neighborhood"].value_counts()

Downtown                   9666
Frankford                  6791
Belair-Edison              6133
Brooklyn                   4528
Cherry Hill                4273
                           ...
Mt Pleasant Park             12
Blythewood                    5
Dundalk Marine Terminal       1
NORTHEASTERN                  1
EASTERN                       1
Name: Neighborhood, Length: 281, dtype: int64

In [12]:
last_6_months = (df['CrimeDate'] >= '2016-06-01') & (df['CrimeDate'] <= '2016-12-31')
last_6_months = df.loc[last_6_months].fillna('Not Registered')
last_6_months

,CrimeDate,CrimeTime,CrimeCode,Location,Description,Inside/Outside,Weapon,Post,District,Neighborhood,Location 1,Total Incidents
0,2016-11-12,02:35:00,3B,300 SAINT PAUL PL,ROBBERY - STREET,O,Not Registered,111,CENTRAL,Downtown,"(39.2924100000, -76.6140800000)",1
1,2016-11-12,02:56:00,3CF,800 S BROADWAY,ROBBERY - COMMERCIAL,I,FIREARM,213,SOUTHEASTERN,Fells Point,"(39.2824200000, -76.5928800000)",1
2,2016-11-12,03:00:00,6D,1500 PENTWOOD RD,LARCENY FROM AUTO,O,Not Registered,413,NORTHEASTERN,Stonewood-Pentwood-Winston,"(39.3480500000, -76.5883400000)",1
3,2016-11-12,03:00:00,6D,6600 MILTON LN,LARCENY FROM AUTO,O,Not Registered,424,NORTHEASTERN,Westfield,"(39.3626300000, -76.5516100000)",1
4,2016-11-12,03:00:00,6E,300 W BALTIMORE ST,LARCENY,O,Not Registered,111,CENTRAL,Downtown,"(39.2893800000, -76.6197100000)",1
...,...,...,...,...,...,...,...,...,...,...,...,...
23341,2016-06-01,21:30:00,3AF,1300 MADISON AVE,ROBBERY - STREET,O,FIREARM,132,CENTRAL,Madison Park,"(39.3032300000, -76.6272000000)",1
23342,2016-06-01,22:00:00,6D,400 S BOND ST,LARCENY FROM AUTO,O,Not Registered,213,SOUTHEASTERN,Fells Point,"(39.2863600000, -76.5954500000)",1
23343,2016-06-01,22:20:00,4E,1500 GUILFORD AVE,COMMON ASSAULT,O,HANDS,311,CENTRAL,Greenmount West,"(39.3069500000, -76.6121100000)",1
23344,2016-06-01,23:00:00,7A,800 LEMMON ST,AUTO THEFT,O,Not Registered,931,SOUTHERN,Hollins Market,"(39.2864200000, -76.6300100000)",1
23345,2016-06-01,23:48:00,4C,3800 3RD ST,AGG. ASSAULT,O,OTHER,913,SOUTHERN,Brooklyn,"(39.2350900000, -76.6084300000)",1

In [13]:
last_6_months['Location'].value_counts()

1000 W PATAPSCO AVE    135
1500 RUSSELL ST         85
Not Registered          82
6300 EASTERN AVE        61
2400 FREDERICK AVE      60
                      ...
3900 PARKSIDE DR         1
600 S PAYSON ST          1
200 E 27TH ST            1
1100 S DECKER AVE        1
3800 LYNDALE AVE         1
Name: Location, Length: 9027, dtype: int64

In [14]:
last_6_months['District'].value_counts()

NORTHEASTERN      3163
SOUTHEASTERN      3074
SOUTHERN          3027
CENTRAL           2866
NORTHERN          2547
NORTHWESTERN      2336
SOUTHWESTERN      2305
EASTERN           2022
WESTERN           1972
SOUTHESTERN         13
NORTHESTERN          9
Not Registered       7
Gay Street           1
Name: District, dtype: int64

In [15]:
last_6_months['Neighborhood'].value_counts()

Downtown                840
Brooklyn                518
Frankford               517
Belair-Edison           483
Cherry Hill             478
                       ...
Villages Of Homeland      2
Morgan Park               1
Blythewood                1
Port Covington            1
EASTERN                   1
Name: Neighborhood, Length: 277, dtype: int64

In [16]:
last_6_months['Weapon'].value_counts()

Not Registered    15082
HANDS              3782
FIREARM            2310
OTHER              1309
KNIFE               859
Name: Weapon, dtype: int64

In [17]:
last_6_months.loc[last_6_months['Weapon'] == 'FIREARM',"Location"].value_counts()

2200 W Cold Spring Ln      19
700 E PRESTON ST           16
400 FONTHILL AVE           13
1000 N MOUNT ST            12
800 W LEXINGTON ST         11
                           ..
1900 CLIFTON AV             1
200 E READ ST               1
PATAPSCO AV & LORENA AV     1
1500 ARGYLE AVE             1
1800 MARYLAND AVE           1
Name: Location, Length: 1544, dtype: int64

In [18]:
last_6_months.loc[last_6_months['Weapon'] == 'FIREARM',"District"].value_counts()

NORTHEASTERN      312
SOUTHERN          295
SOUTHWESTERN      288
CENTRAL           269
NORTHERN          247
EASTERN           232
WESTERN           229
SOUTHEASTERN      225
NORTHWESTERN      211
Not Registered      1
SOUTHESTERN         1
Name: District, dtype: int64

In [19]:
last_6_months.loc[last_6_months['Weapon'] == 'FIREARM',"Neighborhood"].value_counts()

Downtown               76
Brooklyn               67
Sandtown-Winchester    65
Carrollton Ridge       58
Belair-Edison          47
                       ..
South Baltimore         1
Mayfield                1
Seton Business Park     1
Woodberry               1
Fairmont                1
Name: Neighborhood, Length: 239, dtype: int64

In [22]:
last_6_months['CrimeTime'].value_counts()

18:00:00    597
17:00:00    531
22:00:00    523
20:00:00    523
21:00:00    496
           ...
02:56:45      1
1505          1
05:41:00      1
1018          1
0520          1
Name: CrimeTime, Length: 1838, dtype: int64